name: box

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image_main:
      shape: [3, 224, 224]
      type: rgb
      horizon: 2
    image_wrist:
      shape: [3, 224, 224]
      type: rgb
      horizon: 2
    point_cloud:
      shape: [4096, 3]
      type: point_cloud
      horizon: 2
    agent_pos:
      shape: [15]
      type: low_dim
      horizon: 2
  action:
    shape: [15]
    horizon: 15


dataset:
  _target_: diffusion_policy_3d.dataset.marsmind_metaact_dataset_mm.MarsmindMetaActEpisodeDatasetMM
  data_path: /media/viewer/Image_Lab/embod_data/MarsMind_data
  task_name: grasp
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  use_img: true
  use_depth: false
  num_points: ${policy.pointcloud_encoder_cfg.num_points}
